select * from customer_behaviour limit 20;
--- what is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue
from customer_behaviour
group by gender;

--- which customer used a discount but still spent more that average purchase amount?
SELECT customer_id, purchase_amount
FROM customer_behaviour
WHERE discount_applied = 'Yes' 
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_behaviour);

--- which are the top 5 products with the highest avergae review rating?
select item_purchased , round(avg(review_rating::numeric),2) as "average product rating"
from customer_behaviour
group by item_purchased
order by avg(review_rating) desc
limit(5);

--- compare the average purchase amounts between standard and express shipping.
select shipping_type, round(avg(purchase_amount),2)
from customer_behaviour
where shipping_type in ('Standard','Express')
group by shipping_type;

--- do subscribed customers spend more? compare average spend and total revenue between subscribers 
---and non subscribers.
select subscription_status, 
count(customer_id) as total_customer,
Round(avg(purchase_amount),2) as average_spend,
Round(sum(purchase_amount),2) as total_revenue
from customer_behaviour
group by subscription_status
order by average_spend,total_revenue desc;

--- which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
       ROUND(100 * SUM(CASE WHEN LOWER(discount_applied) = 'yes' THEN 1 ELSE 0 end)/ COUNT(*), 2) AS discount_rate
FROM customer_behaviour
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--- segment customers into new,returning and loyal based on the total number of previous 
--- purchases and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer_behaviour
)
select customer_segment, count(*) as "Number Of Customers"
from customer_type
group by customer_segment;

--- what are the top 3 most purchased products within each category.
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by Count(customer_id)desc) as item_rank
from customer_behaviour
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--- are customers who are repeat buyers (more than 5 previous_puchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_behaviour
where previous_purchases > 5
group by subscription_status;

--- what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer_behaviour
group by age_group
order by total_revenue desc;